'use strict';
const data=window.GRAPH_DATA;
const palette={COMPOUND:'#207c80',PROTEIN:'#315a76',GENE:'#788d99',GENES:'#788d99',DISEASE:'#8e6a74',DISEASES:'#8e6a74',PHENOTYPE:'#a5b5bd',PHENOTYPES:'#a5b5bd',MOLECULE:'#57a3a5',ACTIVITY:'#8c899c',EFFECT:'#b39e72',INDICATION:'#658b88',SIDE_EFFECT:'#a98a75',PATHWAY:'#7a9eae',PATHWAYS:'#7a9eae'};
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function entity(n){const text=String(n.title||n.label||n.id).toUpperCase();if(data.slug==='bayesian_network')return String(n.id).toUpperCase();for(const kind of Object.keys(palette).sort((a,b)=>b.length-a.length)){if(text===kind||text.startsWith(kind+'_')||text.startsWith(kind+'\n')||text.startsWith(kind+'/'))return kind;}return text.split(/[ _/\n]/)[0];}
const allNodes=data.nodes.map(n=>{const kind=entity(n),focus=n.shape==='diamond';let label=String(n.label||n.id);if(data.slug!=='ontology'&&data.slug!=='bayesian_network')label=String(n.title||n.id).split('/')[0];return {...n,label,title:escape(n.title||label),kind,shape:focus?'diamond':'dot',size:focus?24:(data.nodes.length>1000?5:10),borderWidth:focus?3:1,color:{background:palette[kind]||'#658999',border:focus?'#153247':'#ffffff'},font:{size:data.nodes.length>1000?0:11,color:'#153247'},hidden:false};});
const allEdges=data.edges.map((e,i)=>({...e,id:i,title:escape(e.title||e.label||''),color:e.title==='increase_efficacy'?'#207c80':e.title==='decrease_efficacy'?'#6a7892':'#a9bdc7',width:1,arrows:'to',smooth:{enabled:true,type:'continuous',roundness:.18}}));
const nodes=new vis.DataSet(allNodes),edges=new vis.DataSet(allEdges);
const small=data.nodes.length<20;
const options={nodes:{chosen:true},edges:{arrowStrikethrough:false},interaction:{hover:true,navigationButtons:true,keyboard:true,hideEdgesOnDrag:data.nodes.length>1000},physics:{enabled:!small,solver:'barnesHut',barnesHut:{gravitationalConstant:-3500,centralGravity:.2,springLength:110,springConstant:.03,avoidOverlap:.3},stabilization:{enabled:true,iterations:data.nodes.length>1000?120:240,updateInterval:30}},layout:{randomSeed:23},configure:false};
if(data.slug==='bayesian_network'){const pos={Compound:{x:0,y:20},Gene:{x:190,y:-120},Protein:{x:300,y:160},Disease:{x:540,y:160}};nodes.update(allNodes.map(n=>({...n,...pos[n.id],fixed:true,size:27,font:{size:16,color:'#153247'}})));}
if(data.slug==='ontology'){options.physics.enabled=true;options.physics.stabilization.iterations=500;options.physics.barnesHut.springLength=240;nodes.update(allNodes.map(n=>({...n,size:20,font:{size:14,color:'#153247'}})));edges.update(allEdges.map(e=>({...e,font:{size:9,color:'#586b77',strokeWidth:3,strokeColor:'#ffffff'},smooth:{enabled:true,type:'curvedCW',roundness:.2}})));}
const network=new vis.Network(document.getElementById('network'),{nodes,edges},options);
const kinds=[...new Set(allNodes.map(n=>n.kind))].sort();
const select=document.getElementById('type');for(const kind of kinds){const o=document.createElement('option');o.value=kind;o.textContent=kind.toLowerCase().replace('_',' ');select.appendChild(o);const item=document.createElement('span');item.textContent=o.textContent;item.style.setProperty('--c',palette[kind]||'#658999');document.getElementById('legend').appendChild(item);}
const status=document.getElementById('status');status.textContent=`${allNodes.length.toLocaleString()} nodes · ${allEdges.length.toLocaleString()} edges`;
let moving=options.physics.enabled;
network.once('stabilizationIterationsDone',()=>{moving=false;network.setOptions({physics:{enabled:false}});document.getElementById('physics').textContent='Enable movement';network.fit({animation:false});});
document.getElementById('fit').onclick=()=>network.fit({animation:true});
document.getElementById('physics').textContent=moving?'Pause movement':'Enable movement';document.getElementById('physics').onclick=()=>{moving=!moving;network.setOptions({physics:{enabled:moving}});document.getElementById('physics').textContent=moving?'Pause movement':'Enable movement';};
select.onchange=()=>{const kind=select.value;const visible=new Set(allNodes.filter(n=>!kind||n.kind===kind).map(n=>n.id));nodes.update(allNodes.map(n=>({id:n.id,hidden:!visible.has(n.id)})));const es=allEdges.map(e=>({id:e.id,hidden:!visible.has(e.from)||!visible.has(e.to)}));edges.update(es);status.textContent=`${visible.size.toLocaleString()} nodes · ${es.filter(e=>!e.hidden).length.toLocaleString()} edges`;network.fit({animation:true});};
function search(){const term=document.getElementById('search').value.trim().toLowerCase();if(!term)return;const matches=allNodes.filter(n=>String(n.id).toLowerCase().includes(term)||String(n.title).toLowerCase().includes(term)||String(n.label).toLowerCase().includes(term));if(!matches.length){status.textContent='No matching node';return;}select.value='';select.onchange();network.selectNodes(matches.map(n=>n.id));if(matches.length===1)network.focus(matches[0].id,{scale:1.5,animation:true});else network.fit({nodes:matches.map(n=>n.id),animation:true});status.textContent=`${matches.length} matching node${matches.length===1?'':'s'}`;}
document.getElementById('find').onclick=search;document.getElementById('search').onkeydown=e=>{if(e.key==='Enter')search();};
document.getElementById('reset').onclick=()=>{document.getElementById('search').value='';select.value='';select.onchange();network.unselectAll();};
